### ISSUE TITLE
Eslint error

### ISSUE THREAD

**Issue by jjj-guo** [oxc-project/eslint-plugin-oxlint#14]
In my project, when I follow the tutorial after configuration,it occur error:
Oops! Something went wrong! :(

ESLint: 7.19.0

Error: ESLint configuration in .eslintrc is invalid:
        - Unexpected top-level property "presets".

**Comment by Djiit** [comment]
Hey, could you provide a minimal reproduction example with a dummy project?

**Comment by rkorzhoff** [comment]
Same here. I have .eslintrc.cjs, and I've added presets: ['plugin:oxlint/recommended'] as described in your docs, but I'm getting the same error. Here is my config:
```
module.exports = {
  extends: ['aurora-vue/vue-3-fsd'],
  parser: 'vue-eslint-parser',
  parserOptions: {
    parser: '@typescript-eslint/parser',
    project: './tsconfig.json',
  },
  presets: ['plugin:oxlint/recommended'],
}
```
ESLint version 8.56.0.

Moreover, it doesn't seem that such a field (`presets`) is described anywhere in the ESLint documentation.

**Comment by Djiit** [comment]
Oh, I see, that's my bad. Indeed the field is `extends` and not `presets`. I'll fix the README.

**Comment by Djiit** [comment]
@rkorzhoff could you please try with `extends` ? I'll merge the PR if working.

**Comment by jjj-guo** [comment]
One more question I want to ask, isn't the latest eslint 8.57, why does the documentation say 9.0

**Comment by Djiit** [comment]
It is 8.57, yes. 9.0 is the next one, still in a beta state (https://eslint.org/blog/2024/02/eslint-v9.0.0-beta.1-released/

**Comment by rkorzhoff** [comment]
@Djiit yep, that way is correct. Thanks!

**Comment by rkorzhoff** [comment]
@Djiit btw, why do `oxlint` allows to specify only `.json` format when run it with `-c` flag? This is very confusing because the main example here is described using flat config, which, according to the ESLint documentation, does not imply the use of `.json`

**Comment by Djiit** [comment]
That's a limitation of oxlint itself indeed. In most case in big projects, you'll be using a shared json rules files with oxlint, and eslinr would extend it with this preset.
