### ISSUE TITLE
The generated files does not match with the source

### ISSUE THREAD

**Issue by d8bauxit8** [oxc-project/eslint-plugin-oxlint#154]
Hy all,

In the lib folder the generated files does not match with the source.
For example, the `src/rules-by-scope.ts` contains `jest/no-conditional-in-test` rule but the `lib/rules-by-scope.(c|m)js` is not.

Can you regenerate this files?

What if, we create a new step in the workflow which includes this generation?

**Comment by Boshen** [comment]
Should be fixed with the latest release.
