### ISSUE TITLE
plugin did not get build

### ISSUE THREAD

**Issue by Sysix** [oxc-project/eslint-plugin-oxlint#171]
After creating #170  I asked myself why the `lib` folder is getting a lint error.  
Then I found out, there is `pnpm build` which need to be executed. 

So the last versions did not get the right list of supported rules. 

Nice to have:
- CI for PR 
- or CI for release

Would like to work on it the next days and update the CI on this project in general.

**Comment by Sysix** [comment]
@Boshen one PR ist ready for review. The next steps (PR) are the following:

- Removing dist folder and [creating it on release](https://github.com/oxc-project/eslint-plugin-oxlint/blob/6114c84f796e28bcead4f38ddde4d81c396b352d/.github/workflows/release.yml#L37)
- oxc-bot for prettier auto commit. Copying from https://github.com/oxc-project/oxc/blob/main/.github/workflows/autofix.yml

Please tell when something should not be done 🫶

**Comment by Boshen** [comment]
> @Boshen one PR ist ready for review. The next steps (PR) are the following:
> 
> * Removing dist folder and [creating it on release](https://github.com/oxc-project/eslint-plugin-oxlint/blob/6114c84f796e28bcead4f38ddde4d81c396b352d/.github/workflows/release.yml#L37)
> * oxc-bot for prettier auto commit. Copying from https://github.com/oxc-project/oxc/blob/main/.github/workflows/autofix.yml
> 
> Please tell when something should not be done 🫶

Sounds good to me, have fun!
