### ISSUE TITLE
Wish the name was eslint-config-oxlint to adhire to how eslint-{plugin/config}-prettier works

### ISSUE THREAD

**Issue by kbrilla** [oxc-project/eslint-plugin-oxlint#186]
Name of this eslint plugin can sound like it run oxlint from inside eslint just like eslint-plugin-prettier run prettier as eslint rule, while eslint-config-prettier disabled eslint rules that are solved by prettier.

**Comment by Boshen** [comment]
Feel free to send a PR to update the README for clarity.
