### ISSUE TITLE
 How to confirm the eslint-oxlint success of my project?

### ISSUE THREAD

**Issue by jjj-guo** [oxc-project/eslint-plugin-oxlint#25]
I followed the documentation, but it still feels like eslint is taking a long time to run. How do I make sure the plugin is running and how do I view the output?

`precommit": "npx oxlint && eslint src --quiet --ext .jsx,.js,.tsx,.ts -f json -o ./.ci/eslint.json",`

**Comment by Djiit** [comment]
Hey, yes, you can try a `eslint --print-config file.js` (target any file that should be linted, just to test) and see which rules apply.
