### ISSUE TITLE
Missing type export

### ISSUE THREAD

**Issue by faner11** [oxc-project/eslint-plugin-oxlint#46]
When I turn on ts strictTypeChecked, I get the error
<img width="787" alt="image" src="https://github.com/oxc-project/eslint-plugin-oxlint/assets/26560612/e41aba96-4e15-41e1-b69c-c13f71665d27">

Wish it was possible to export types

 
<img width="1233" alt="image" src="https://github.com/oxc-project/eslint-plugin-oxlint/assets/26560612/3e809ca2-d5f7-4447-9616-789f399e1f50">

**Comment by Djiit** [comment]
This package's main files are not currently in TS. Any contributions are welcome!
