### ISSUE TITLE
Not working in non-flat config usage

### ISSUE THREAD

**Issue by Djiit** [oxc-project/eslint-plugin-oxlint#5]
Hey team,

Looks like the plugin is not adding nor removing any rules on an empty configuration.

Repro:

```bash
npx create-react-app eslint-repro
cd eslint-repro
npm init @eslint/config
npx eslint --print-config src/App.js # check output
npm i eslint-plugin-oxlint
# here, add it to the eslint config's plugin list, then
npx eslint --print-config src/App.js  # same output (some rules should be off'd)
```

We might be missing a couple test to ensure final eslint config has been modified.

edit: looks like I'm not using eslint 9.0.0 defaults yet, and it might be related.
edit2: looks like rules are the same ib both configuration formats ...: https://eslint.org/docs/latest/extend/plugin-migration-flat-config#migrating-rules-for-flat-config

**Comment by Djiit** [comment]
I'm not sure then how to use this with a json config file.

**Comment by Djiit** [comment]
Hi @Dunqing , is there anything I could try to help on this ?

**Comment by Dunqing** [comment]
Sorry, I only tested flat config.
