### ISSUE TITLE
Use eslint-doc-generator

### ISSUE THREAD

**Issue by Djiit** [oxc-project/eslint-plugin-oxlint#8]
Could this repo benefits from https://github.com/bmish/eslint-doc-generator ?

**Comment by Dunqing** [comment]
Yeah, I think it's helpful

**Comment by Djiit** [comment]
Great, I'll try to find some time to work on this.

**Comment by Dunqing** [comment]
Thank you!!

**Comment by Boshen** [comment]
Close as stale for house keeping (blocked by upstream).
